Using Theano backend.
INFO:root:Acquiring data/wn18/wordnet-mlj12-train.txt ..
INFO:root:Acquiring data/wn18/wordnet-mlj12-valid.txt ..
INFO:root:Acquiring data/wn18/wordnet-mlj12-test.txt ..
INFO:root:Samples: 141442, no. batches: 10 -> batch size: 14145
INFO:root:Epoch no. 1 of 500 (samples: 141442)
INFO:root:Loss: 3.3282 +/- 0.0046
INFO:root:Epoch no. 2 of 500 (samples: 141442)
INFO:root:Loss: 3.2374 +/- 0.0449
INFO:root:Epoch no. 3 of 500 (samples: 141442)
INFO:root:Loss: 2.8729 +/- 0.124
INFO:root:Epoch no. 4 of 500 (samples: 141442)
INFO:root:Loss: 2.4342 +/- 0.0601
INFO:root:Epoch no. 5 of 500 (samples: 141442)
INFO:root:Loss: 2.2296 +/- 0.0167
INFO:root:Epoch no. 6 of 500 (samples: 141442)
INFO:root:Loss: 2.1319 +/- 0.0101
INFO:root:Epoch no. 7 of 500 (samples: 141442)
INFO:root:Loss: 2.0722 +/- 0.0083
INFO:root:Epoch no. 8 of 500 (samples: 141442)
INFO:root:Loss: 2.034 +/- 0.015
INFO:root:Epoch no. 9 of 500 (samples: 141442)
INFO:root:Loss: 1.9996 +/- 0.0098
INFO:root:Epoch no. 10 of 500 (samples: 141442)
INFO:root:Loss: 1.9657 +/- 0.0126
INFO:root:Epoch no. 11 of 500 (samples: 141442)
INFO:root:Loss: 1.946 +/- 0.0104
INFO:root:Epoch no. 12 of 500 (samples: 141442)
INFO:root:Loss: 1.9255 +/- 0.013
INFO:root:Epoch no. 13 of 500 (samples: 141442)
INFO:root:Loss: 1.9069 +/- 0.0099
INFO:root:Epoch no. 14 of 500 (samples: 141442)
INFO:root:Loss: 1.894 +/- 0.015
INFO:root:Epoch no. 15 of 500 (samples: 141442)
INFO:root:Loss: 1.8788 +/- 0.0189
INFO:root:Epoch no. 16 of 500 (samples: 141442)
INFO:root:Loss: 1.8655 +/- 0.0201
INFO:root:Epoch no. 17 of 500 (samples: 141442)
INFO:root:Loss: 1.8505 +/- 0.0151
INFO:root:Epoch no. 18 of 500 (samples: 141442)
INFO:root:Loss: 1.8404 +/- 0.0137
INFO:root:Epoch no. 19 of 500 (samples: 141442)
INFO:root:Loss: 1.8365 +/- 0.0114
INFO:root:Epoch no. 20 of 500 (samples: 141442)
INFO:root:Loss: 1.8215 +/- 0.0166
INFO:root:Epoch no. 21 of 500 (samples: 141442)
INFO:root:Loss: 1.8142 +/- 0.0149
INFO:root:Epoch no. 22 of 500 (samples: 141442)
INFO:root:Loss: 1.8054 +/- 0.0142
INFO:root:Epoch no. 23 of 500 (samples: 141442)
INFO:root:Loss: 1.7866 +/- 0.0152
INFO:root:Epoch no. 24 of 500 (samples: 141442)
INFO:root:Loss: 1.7749 +/- 0.0141
INFO:root:Epoch no. 25 of 500 (samples: 141442)
INFO:root:Loss: 1.7693 +/- 0.0171
INFO:root:Epoch no. 26 of 500 (samples: 141442)
INFO:root:Loss: 1.7658 +/- 0.0122
INFO:root:Epoch no. 27 of 500 (samples: 141442)
INFO:root:Loss: 1.755 +/- 0.0124
INFO:root:Epoch no. 28 of 500 (samples: 141442)
INFO:root:Loss: 1.7485 +/- 0.0183
INFO:root:Epoch no. 29 of 500 (samples: 141442)
INFO:root:Loss: 1.7388 +/- 0.0133
INFO:root:Epoch no. 30 of 500 (samples: 141442)
INFO:root:Loss: 1.7264 +/- 0.0122
INFO:root:Epoch no. 31 of 500 (samples: 141442)
INFO:root:Loss: 1.716 +/- 0.013
INFO:root:Epoch no. 32 of 500 (samples: 141442)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/hyper-cli.py", line 324, in <module>
    main(sys.argv[1:])
  File "./bin/hyper-cli.py", line 293, in main
    visualize=is_visualize)
  File "/home/insight/.local/lib/python3.4/site-packages/hyper-0.0.1-py3.4.egg/hyper/learning/core.py", line 185, in pairwise_training
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/models.py", line 409, in fit
    sample_weight=sample_weight)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/training.py", line 1052, in fit
    callback_metrics=callback_metrics)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/training.py", line 790, in _fit_loop
    outs = f(ins_batch)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/backend/theano_backend.py", line 518, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError: 
Apply node that caused the error: Elemwise{mul,no_inplace}(Reshape{3}.0, Reshape{3}.0)
Toposort index: 55
Inputs types: [TensorType(float32, (False, False, True)), TensorType(float32, 3D)]
Inputs shapes: [(42435, 100, 1), (42435, 100, 100)]
Inputs strides: [(800, 4, 4), (40000, 400, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Sum{axis=[1], acc_dtype=float64}(Elemwise{mul,no_inplace}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "./bin/hyper-cli.py", line 293, in main
    visualize=is_visualize)
  File "/home/insight/.local/lib/python3.4/site-packages/hyper-0.0.1-py3.4.egg/hyper/learning/core.py", line 78, in pairwise_training
    merge_layer = Merge([predicate_encoder, entity_encoder], mode=merge_function, output_shape=lambda _: (None, 1))
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 1116, in __init__
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 153, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/home/insight/.local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/engine/topology.py", line 1193, in call
    return self.mode(inputs, **arguments)
  File "/home/insight/.local/lib/python3.4/site-packages/hyper-0.0.1-py3.4.egg/hyper/layers/core.py", line 28, in latent_distance_binary_merge_function
    return merge_function(args, similarity=similarity_function)
  File "/home/insight/.local/lib/python3.4/site-packages/hyper-0.0.1-py3.4.egg/hyper/layers/binary/merge_functions.py", line 186, in bilinear_merge_function
    bilinear_transformation = (rx * rW).sum(1)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
